# Stage 1 : Build du healthcheck Go
FROM louislam/uptime-kuma:builder-go AS healthcheck_builder

# Stage 2 : Build du frontend et dépendances
FROM louislam/uptime-kuma:base2 AS app_builder
WORKDIR /app
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build
RUN npm prune --omit=dev --legacy-peer-deps
COPY --from=healthcheck_builder /app/extra/healthcheck /app/extra/healthcheck

# Stage 3 : Image finale (Release)
FROM louislam/uptime-kuma:base2 AS release
WORKDIR /app

ENV UPTIME_KUMA_IS_CONTAINER=1 \
    NODE_ENV=production

# On copie les fichiers EN DONNANT la propriété à l'utilisateur 'node'
COPY --from=app_builder --chown=node:node /app /app

# On crée le dossier data et on s'assure qu'il appartient à node
RUN mkdir -p /app/data && chown node:node /app/data

USER node
EXPOSE 3001
VOLUME /app/data

HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server/server.js"]